# Test Cluster
services:
  bootstrap:
    image: com.hellblazer.sky/sky-image:0.0.1-SNAPSHOT
    environment:
      GENESIS: 'true'
      API_ENDPOINT: '0.0.0.0:8123'
      APPROACH_ENDPOINT: '0.0.0.0:8124'
      CLUSTER_ENDPOINT: '0.0.0.0:8125'
      ADVERTISED_ENDPOINT: '172.17.0.2:8125'
    network_mode: bridge

  kernel1:
    image: com.hellblazer.sky/sky-image:0.0.1-SNAPSHOT
    environment:
      GENESIS: 'true'
      APPROACHES: '172.17.0.2:8124'
      SEEDS: '172.17.0.2:8125#8123'
      API_ENDPOINT: '0.0.0.0:9123'
      APPROACH_ENDPOINT: '0.0.0.0:9124'
      CLUSTER_ENDPOINT: '0.0.0.0:9125'
      ADVERTISED_ENDPOINT: '172.17.0.2:9125'
    network_mode: bridge
    depends_on:
      bootstrap:
        condition: service_started

  kernel2:
    image: com.hellblazer.sky/sky-image:0.0.1-SNAPSHOT
    environment:
      GENESIS: 'true'
      APPROACHES: '172.17.0.2:8124'
      SEEDS: '172.17.0.2:8125#8123'
      API_ENDPOINT: '0.0.0.0:10123'
      APPROACH_ENDPOINT: '0.0.0.0:10124'
      CLUSTER_ENDPOINT: '0.0.0.0:10125'
      ADVERTISED_ENDPOINT: '172.17.0.2:10125'
    network_mode: bridge
    depends_on:
      bootstrap:
        condition: service_started

  kernel3:
    image: com.hellblazer.sky/sky-image:0.0.1-SNAPSHOT
    environment:
      GENESIS: 'true'
      APPROACHES: '172.17.0.2:8124'
      SEEDS: '172.17.0.2:8125#8123'
      API_ENDPOINT: '0.0.0.0:11123'
      APPROACH_ENDPOINT: '0.0.0.0:11124'
      CLUSTER_ENDPOINT: '0.0.0.0:11125'
      ADVERTISED_ENDPOINT: '172.17.0.2:11125'
    network_mode: bridge
    depends_on:
      bootstrap:
        condition: service_started
