# Test Cluster
services:
  bootstrap:
    image: com.hellblazer.sky/sky-image:0.0.1-SNAPSHOT
    ports:
      - 8123:8123
      - 8124:8124
      - 8125:8125
    environment:
      GENESIS: 'true'

  kernel1:
    image: com.hellblazer.sky/sky-image:0.0.1-SNAPSHOT
    ports:
      - 9123:8123
      - 9124:8124
      - 9125:8125
    environment:
      GENESIS: 'true'
      SEEDS: 'F00@localhost:8123'
      APPROACHES: 'localhost:8124'

  kernel2:
    image: com.hellblazer.sky/sky-image:0.0.1-SNAPSHOT
    ports:
      - 10123:8123
      - 10124:8124
      - 10125:8125
    environment:
      GENESIS: 'true'
      SEEDS: 'F00@localhost:8123'
      APPROACHES: 'localhost:8124'

  kernel3:
    image: com.hellblazer.sky/sky-image:0.0.1-SNAPSHOT
    ports:
      - 11123:8123
      - 11124:8124
      - 11125:8125
    environment:
      GENESIS: 'true'
      SEEDS: 'F00@localhost:8123'
      APPROACHES: 'localhost:8124'
