# Test Cluster
services:
  bootstrap:
    image: com.hellblazer.sky/sky-image:0.0.1-SNAPSHOT
    environment:
      GENESIS: 'true'
      BIND_INTERFACE: eth0
      API: 50000
      APPROACH: 50001
      CLUSTER: 50002
    network_mode: bridge

  kernel1:
    image: com.hellblazer.sky/sky-image:0.0.1-SNAPSHOT
    environment:
      GENESIS: 'true'
      APPROACHES: '172.17.0.2:50001'
      SEEDS: '172.17.0.2:50002#50000'
      BIND_INTERFACE: eth0
    network_mode: bridge
    depends_on:
      bootstrap:
        condition: service_started

  kernel2:
    image: com.hellblazer.sky/sky-image:0.0.1-SNAPSHOT
    environment:
      GENESIS: 'true'
      APPROACHES: '172.17.0.2:50001'
      SEEDS: '172.17.0.2:50002#50000'
      BIND_INTERFACE: eth0
    network_mode: bridge
    depends_on:
      bootstrap:
        condition: service_started

  kernel3:
    image: com.hellblazer.sky/sky-image:0.0.1-SNAPSHOT
    environment:
      GENESIS: 'true'
      APPROACHES: '172.17.0.2:50001'
      SEEDS: '172.17.0.2:50002#50000'
      BIND_INTERFACE: eth0
    network_mode: bridge
    depends_on:
      bootstrap:
        condition: service_started
