
viewGossipDuration: PT0H0M00.03S

choamParameters:
  checkpointBlockDelta: 7
  gossipDuration: PT0H0M00.03S
  synchronizationCycles: 10
  regenerationCycles: 10

producerParameters:
  maxBatchByteSize: 10485760
  maxBatchCount: 3000
  gossipDuration: PT0H0M00.03S
  ethereal:
    epochLength: 20

domain:
  dbURL: "jdbc:h2:mem:sql;DB_CLOSE_DELAY=-1"
  dhtOperationsTimeout: PT0H0M10S
  dhtDbUrl: "jdbc:h2:mem:dht;DB_CLOSE_DELAY=-1"
  checkpointBaseDir: ./check-points
  dhtOpsFrequency: PT0H0M00.001S
  dhtFpr: 0.000125
  dhtEventValidTO: PT0H0M10S
  dhtBias: 3
  jdbcMaxConnections: 10
  dhtPbyz: 0.01
  kerlSpaceDuration: PT0H0M00.5S

identity:
  keyStore: ".id"
  keyStoreType: JCEKS
  kerlURL: "jdbc:h2:file:./kerl-state"
  identityFile: ".digest"
  digestAlgorithm: BLAKE2B_256
  signatureAlgorithm: ED_25519
  encryptionAlgorithm: X_25519
